# Generated by Django 4.0.7 on 2022-09-29 08:31

from django.db import migrations


def migrate_forward(apps, schema_editor):
    Entity = apps.get_model("tournesol", "Entity")
    Poll = apps.get_model("tournesol", "Poll")
    poll_video = Poll.objects.get(name="videos")
    poll_presidentielle2022 = Poll.objects.get(name="presidentielle2022")
    for entity in Entity.objects.filter(type="video").iterator():
        create_poll_rating_entity(apps, poll_video, entity)

    for entity in Entity.objects.filter(type="candidate_fr_2022").iterator():
        create_poll_rating_entity(apps, poll_presidentielle2022, entity)


def create_poll_rating_entity(apps, poll, entity):
    EntityPollRating = apps.get_model("tournesol", "EntityPollRating")
    rating = EntityPollRating()
    rating.poll = poll
    rating.entity = entity
    rating.tournesol_score = entity.tournesol_score
    rating.n_comparisons = entity.rating_n_ratings
    rating.n_contributors = entity.rating_n_contributors
    rating.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tournesol', '0048_alter_poll_algorithm'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrations.RunPython.noop)
    ]
